### ISSUE TITLE
如何解码mflac0？

### ISSUE THREAD

**Issue by GitJoBo** [zeroclear/unlock-mflac-20220931#1]
我尝试了demo代码，补全了缺失组件，提示 解锁失败67615453

**Comment by zeroclear** [comment]
程序只能识别两种格式，其他的会提示解锁失败，后面跟着格式信息。这串数字翻译成文本是STag，确实和mflac格式不一样，你可以发个样本给我看看。

**Comment by GitJoBo** [comment]
支持哪两种格式？我看代码里只支持.mflac格式的。样本是指音乐发你吗？链接: https://pan.baidu.com/s/1OcPwvusV9-fA9dauZfCXQw?pwd=fx23 提取码: fx23 复制这段内容后打开百度网盘手机App，操作更方便哦 这是音乐原件，提示只支持.mflac文件。注释限制后 提示 解码失败67615453

**Comment by zeroclear** [comment]
只支持mflac的两种类型，不支持mflac0。你的样本我看了，结尾是STag，根据其他人的研究，这种格式没有内嵌的key，想解密的话需要在其他地方（如缓存目录）找到对应的key文件。这个项目可能对你有帮助：https://github.com/bczhc/qmc-decode

**Comment by GitJoBo** [comment]
qmc-decode这个我有关注，主要是对应的key文件不清楚怎么获取，方便指导一下吗？邮箱jobo_jun@foxmail.com 可有偿

**Comment by zeroclear** [comment]
![key路径](https://user-images.githubusercontent.com/16979504/209559172-e9c44570-992d-4933-a85f-5a723099c86f.png)
作者动手之前已经说过了，我看了一眼，应该没有变化，用sqlite工具打开就行了。

**Comment by zeroclear** [comment]
唉，没动静了，连有没有帮到别人都不知道

**Comment by GitJoBo** [comment]
感谢指导，这几天阳了，没能及时回馈万分抱歉
